spring.application.name=urban-eats

spring.datasource.url=jdbc:mysql://localhost:3306/urban_eats?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=none
spring.show-sql=true
spring.jpa.properties.hibernate.format_sql=true